"""Transfer a reference person's appearance onto a driving video's motion."""

from video_character_skill.compositor import (
    SOURCE_HARDEN_THRESHOLD,
    SOURCE_REMOVAL_DILATION_RADIUS,
    SOURCE_REMOVAL_THRESHOLD,
    CompositeError,
    CompositeReport,
    HardenedUnionCompositeReport,
    SourceRemovalCompositeReport,
    UnionCompositeReport,
    composite_frame,
    composite_video,
    composite_video_hardened_union,
    composite_video_source_removal,
    composite_video_union,
    hardened_union_alpha,
    removal_effective_alpha,
    source_removal_mask,
    union_alpha,
)
from video_character_skill.masks import (
    MaskDecodeError,
    decode_object_mask,
    decode_rle,
    mask_area_ratio,
    mask_bbox,
)
from video_character_skill.schemas import (
    CharacterOrientation,
    DrivingVideo,
    IdentityElement,
    Job,
    JobStatus,
    MaskFrame,
    MatteCodec,
    MatteVideo,
    MattingRequest,
    ObjectMask,
    ReferenceImage,
    ResultVideo,
    SegmentationRequest,
    SourceVideo,
    TransferRequest,
    VideoEditRequest,
    VideoMaskTrack,
)

__all__ = [
    "SOURCE_HARDEN_THRESHOLD",
    "SOURCE_REMOVAL_DILATION_RADIUS",
    "SOURCE_REMOVAL_THRESHOLD",
    "CharacterOrientation",
    "CompositeError",
    "CompositeReport",
    "HardenedUnionCompositeReport",
    "SourceRemovalCompositeReport",
    "MaskDecodeError",
    "DrivingVideo",
    "IdentityElement",
    "Job",
    "JobStatus",
    "MaskFrame",
    "MatteCodec",
    "MatteVideo",
    "MattingRequest",
    "ObjectMask",
    "ReferenceImage",
    "ResultVideo",
    "SegmentationRequest",
    "SourceVideo",
    "TransferRequest",
    "UnionCompositeReport",
    "VideoEditRequest",
    "VideoMaskTrack",
    "composite_frame",
    "composite_video",
    "composite_video_hardened_union",
    "composite_video_source_removal",
    "composite_video_union",
    "decode_object_mask",
    "decode_rle",
    "hardened_union_alpha",
    "mask_area_ratio",
    "mask_bbox",
    "removal_effective_alpha",
    "source_removal_mask",
    "union_alpha",
]

__version__ = "0.0.1"
